### PR TITLE
Affix navigation

### PR DESCRIPTION
**Pull request by bernardodiasc**
With this PR the navigation anchor related to the current section will be activate. Unfortunately is working only with `h1`, soon to be fixed, not a bug, it's more a problem with the logic used.

Preview: http://bernardodiasc.github.io/inline-docs/

### CODE REVIEW

**Comment by joshwnj** [comment]
Looks good! Before I merge, could you please remove the filenames from the nav (http://screencast.com/t/3ctwCQh59HU)

Longer-term I'm anticipating that a section might come from multiple files.

Thanks

**Comment by bernardodiasc** [comment]
About this PR, I'm thinking in try another logic, maybe store all headers positions and content height only once and while scrolling update both active menu and persistent header. Was checking the filter method, but have performance concerns (see also http://jsperf.com/filter-method-cost). Any thought about this, in general?

**Comment by joshwnj** [comment]
Yes, I think it makes sense to combine those 2.  Perhaps store all positions once up front, and then emit an event when we scroll to a different section? The affix nav and the side nav can both listen for that same event.  Sound good?

I think `.filter` will perform fine for this case.

**Comment by bernardodiasc** [comment]
Cool. I'll send in a new PR.

> Longer-term I'm anticipating that a section might come from multiple files.

This is interesting by the way, i can see why.

**Pull request closed without merging**
